name: Dummy Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dummy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run dummy check
        run: |
          exit 1